  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./FleetMgmt.IdentityServer/scripts:/usr/src/app
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'