version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - ./FleetMgmt.IdentityServer/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  fleetmgmt.identityserver:
    image: ${DOCKER_REGISTRY-}fleetmgmtidentityserver
    build:
      context: .
      dockerfile: FleetMgmt.IdentityServer/Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - sqlserver