version: "3.7"

networks:
  fleetmgmt-api-dev:
    driver: bridge

services:
    web:
        container_name: fleetmgmt-identity
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        networks:
            - fleetmgmt-api-dev